-- Drinks catalog for autocomplete with ABV and default note
-- Run in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS drinks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  category TEXT,
  abv DECIMAL(4, 2),
  default_note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_drinks_name_lower ON drinks (lower(name));

-- RLS: drinks is a public read-only catalog
ALTER TABLE drinks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read drinks" ON drinks
  FOR SELECT USING (true);

-- Seed common drinks with ABV and category/note
-- Run once; if you need to re-run, truncate first: TRUNCATE drinks;
INSERT INTO drinks (name, category, abv, default_note) VALUES
  ('Beer', 'Beer', 5, 'Beer'),
  ('IPA', 'Beer', 6.5, 'India Pale Ale'),
  ('Lager', 'Beer', 5, 'Lager'),
  ('Pilsner', 'Beer', 5, 'Pilsner'),
  ('Stout', 'Beer', 4.5, 'Stout'),
  ('Wheat Beer', 'Beer', 5, 'Wheat Beer'),
  ('Red Wine', 'Wine', 13, 'Red Wine'),
  ('White Wine', 'Wine', 12, 'White Wine'),
  ('Rose Wine', 'Wine', 12, 'Rose'),
  ('Champagne', 'Wine', 12, 'Champagne'),
  ('Prosecco', 'Wine', 11, 'Prosecco'),
  ('Vodka', 'Spirit', 40, 'Vodka'),
  ('Gin', 'Spirit', 40, 'Gin'),
  ('Rum', 'Spirit', 40, 'Rum'),
  ('Whiskey', 'Spirit', 40, 'Whiskey'),
  ('Bourbon', 'Spirit', 45, 'Bourbon'),
  ('Tequila', 'Spirit', 40, 'Tequila'),
  ('Mezcal', 'Spirit', 40, 'Mezcal'),
  ('Margarita', 'Cocktail', 15, 'Tequila cocktail'),
  ('Martini', 'Cocktail', 20, 'Gin or vodka cocktail'),
  ('Old Fashioned', 'Cocktail', 25, 'Whiskey cocktail'),
  ('Whiskey Sour', 'Cocktail', 18, 'Whiskey cocktail'),
  ('Mojito', 'Cocktail', 12, 'Rum cocktail'),
  ('Negroni', 'Cocktail', 24, 'Gin cocktail'),
  ('Gin and Tonic', 'Cocktail', 10, 'Gin cocktail'),
  ('Moscow Mule', 'Cocktail', 10, 'Vodka cocktail'),
  ('Cosmopolitan', 'Cocktail', 15, 'Vodka cocktail'),
  ('Grey Goose Vodka', 'Vodka', 40, 'French vodka'),
  ('Absolut Vodka', 'Vodka', 40, 'Swedish vodka'),
  ('Ketel One', 'Vodka', 40, 'Dutch vodka'),
  ('Smirnoff', 'Vodka', 40, 'Vodka'),
  ('Hendricks Gin', 'Gin', 41.4, 'Scottish gin'),
  ('Tanqueray', 'Gin', 47.3, 'London dry gin'),
  ('Bacardi Rum', 'Rum', 40, 'White rum'),
  ('Jameson', 'Whiskey', 40, 'Irish whiskey'),
  ('Jack Daniels', 'Whiskey', 40, 'Tennessee whiskey'),
  ('Johnnie Walker', 'Whiskey', 40, 'Blended Scotch'),
  ('Macallan', 'Whiskey', 40, 'Single malt Scotch'),
  ('Corona', 'Beer', 4.6, 'Mexican lager'),
  ('Heineken', 'Beer', 5, 'Dutch lager'),
  ('Guinness', 'Beer', 4.2, 'Irish stout'),
  ('Stella Artois', 'Beer', 5, 'Belgian lager'),
  ('Sierra Nevada', 'Beer', 5.6, 'American pale ale'),
  ('Pale Ale', 'Beer', 5.5, 'Pale Ale'),
  ('Amber Ale', 'Beer', 5.5, 'Amber Ale'),
  ('Porter', 'Beer', 5, 'Porter'),
  ('Saison', 'Beer', 6, 'Belgian farmhouse ale'),
  ('Double IPA', 'Beer', 8, 'Imperial IPA'),
  ('Hefeweizen', 'Beer', 5.5, 'German wheat beer'),
  ('Blue Moon', 'Beer', 5.4, 'Belgian wheat'),
  ('Modelo', 'Beer', 4.4, 'Mexican lager'),
  ('Asahi', 'Beer', 5, 'Japanese lager'),
  ('Sapporo', 'Beer', 5, 'Japanese lager'),
  ('Tsingtao', 'Beer', 4.7, 'Chinese lager'),
  ('Dos Equis', 'Beer', 4.5, 'Mexican lager'),
  ('Red Stripe', 'Beer', 4.7, 'Jamaican lager'),
  ('Pinot Noir', 'Wine', 13, 'Red wine'),
  ('Cabernet Sauvignon', 'Wine', 13.5, 'Red wine'),
  ('Merlot', 'Wine', 13, 'Red wine'),
  ('Malbec', 'Wine', 14, 'Red wine'),
  ('Shiraz', 'Wine', 14, 'Red wine'),
  ('Chardonnay', 'Wine', 13, 'White wine'),
  ('Sauvignon Blanc', 'Wine', 12, 'White wine'),
  ('Pinot Grigio', 'Wine', 12, 'White wine'),
  ('Riesling', 'Wine', 11, 'White wine'),
  ('Moscato', 'Wine', 7, 'Sweet white wine'),
  ('Cava', 'Wine', 11.5, 'Spanish sparkling'),
  ('Port', 'Wine', 20, 'Fortified wine'),
  ('Sherry', 'Wine', 17, 'Fortified wine'),
  ('Belvedere', 'Vodka', 40, 'Polish vodka'),
  ('Titos', 'Vodka', 40, 'American vodka'),
  ('Stolichnaya', 'Vodka', 40, 'Russian vodka'),
  ('Ciroc', 'Vodka', 40, 'French grape vodka'),
  ('Bombay Sapphire', 'Gin', 40, 'London dry gin'),
  ('Beefeater', 'Gin', 40, 'London dry gin'),
  ('White Rum', 'Rum', 40, 'White rum'),
  ('Dark Rum', 'Rum', 40, 'Dark rum'),
  ('Spiced Rum', 'Rum', 40, 'Spiced rum'),
  ('Captain Morgan', 'Rum', 35, 'Spiced rum'),
  ('Havana Club', 'Rum', 40, 'Cuban rum'),
  ('Mount Gay', 'Rum', 43, 'Barbados rum'),
  ('Malibu', 'Rum', 21, 'Coconut rum'),
  ('Kraken', 'Rum', 47, 'Black spiced rum'),
  ('Glenfiddich', 'Whiskey', 40, 'Single malt Scotch'),
  ('Glenlivet', 'Whiskey', 40, 'Single malt Scotch'),
  ('Woodford Reserve', 'Whiskey', 45.2, 'Bourbon'),
  ('Bulleit Bourbon', 'Whiskey', 45, 'Bourbon'),
  ('Crown Royal', 'Whiskey', 40, 'Canadian whisky'),
  ('Maker Mark', 'Whiskey', 45, 'Bourbon'),
  ('Jim Beam', 'Whiskey', 40, 'Bourbon'),
  ('Wild Turkey', 'Whiskey', 40.5, 'Bourbon'),
  ('Lagavulin', 'Whiskey', 43, 'Islay Scotch'),
  ('Blanco Tequila', 'Tequila', 40, 'Silver tequila'),
  ('Reposado Tequila', 'Tequila', 40, 'Aged tequila'),
  ('Patron', 'Tequila', 40, 'Premium tequila'),
  ('Don Julio', 'Tequila', 40, 'Premium tequila'),
  ('Jose Cuervo', 'Tequila', 40, 'Tequila'),
  ('Casamigos', 'Tequila', 40, 'Tequila'),
  ('Brandy', 'Spirit', 40, 'Brandy'),
  ('Cognac', 'Spirit', 40, 'French brandy'),
  ('Hennessy', 'Cognac', 40, 'Cognac'),
  ('Remy Martin', 'Cognac', 40, 'Cognac'),
  ('Sake', 'Sake', 15, 'Japanese rice wine'),
  ('Soju', 'Spirit', 20, 'Korean spirit'),
  ('Cachaca', 'Spirit', 40, 'Brazilian spirit'),
  ('Amaretto', 'Liqueur', 28, 'Almond liqueur'),
  ('Baileys', 'Liqueur', 17, 'Irish cream'),
  ('Kahlua', 'Liqueur', 20, 'Coffee liqueur'),
  ('Grand Marnier', 'Liqueur', 40, 'Orange liqueur'),
  ('Cointreau', 'Liqueur', 40, 'Orange liqueur'),
  ('Jagermeister', 'Liqueur', 35, 'Herbal liqueur'),
  ('Limoncello', 'Liqueur', 30, 'Lemon liqueur'),
  ('Campari', 'Liqueur', 25, 'Bitter liqueur'),
  ('Aperol', 'Liqueur', 11, 'Italian bitter'),
  ('Manhattan', 'Cocktail', 22, 'Whiskey cocktail'),
  ('Daiquiri', 'Cocktail', 12, 'Rum cocktail'),
  ('Pina Colada', 'Cocktail', 10, 'Rum cocktail'),
  ('Bloody Mary', 'Cocktail', 12, 'Vodka cocktail'),
  ('Aperol Spritz', 'Cocktail', 8, 'Prosecco cocktail'),
  ('Espresso Martini', 'Cocktail', 20, 'Vodka coffee cocktail'),
  ('Paloma', 'Cocktail', 10, 'Tequila cocktail'),
  ('Mai Tai', 'Cocktail', 15, 'Rum cocktail'),
  ('Cider', 'Cider', 5, 'Apple cider'),
  ('Hard Seltzer', 'Seltzer', 5, 'Spiked seltzer');